<?php

namespace Francysk\Framework\Core\Config;

if ( !defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true )
    die();

class FieldsClassParams
{
    const DECORATOR = "FRANCYSKFRAEMWORK_DECORATOR";
    const MODEL = "FRANCYSKFRAEMWORK_MODEL";
    const ENTITY = "FRANCYSKFRAEMWORK_ENTITY";
    const COLLECTION_RESULT = "FRANCYSKFRAEMWORK_COLLECTIONRESULT";
    const SYSTEM_FRAEMWORK = "FRANCYSKFRAEMWORK_SYSTEM";
    const FUNCTION_DECORATOR = "FRANCYSKFRAEMWORK_FUNCTION_DECORATOR";

    const NAV_COUNT = "ELEMENT_COUNT";

    const REQUEST_FITLER_SECTION = "REQUEST_FILTER_SECTION";
    const REQUEST_FILTER_ELEMENT = "REQUEST_FILTER_ELEMENT";

    const SAVE_SET = "SETSAVE_ITEMS_NAME";
    const SAVE_GET = "GETSAVE_ITEMS_NAME";
}
